Traceback (most recent call last):
  File "/n/home09/michaelzhao/Downloads/topicexpan/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/n/home09/michaelzhao/Downloads/topicexpan/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'r'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/home09/michaelzhao/Downloads/thesis/topic_taxonomy_expansion/sweep_bart.py", line 137, in <module>
    main()
  File "/n/home09/michaelzhao/Downloads/thesis/topic_taxonomy_expansion/sweep_bart.py", line 20, in main
    r = config.r  # LoRA rank
        ^^^^^^^^
  File "/n/home09/michaelzhao/Downloads/topicexpan/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 167, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'r'
